# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatWindow(object):
    def setupUi(self, ChatWindow):
        ChatWindow.setObjectName("ChatWindow")
        ChatWindow.resize(663, 478)
        ChatWindow.setMinimumSize(QtCore.QSize(663, 478))
        ChatWindow.setMaximumSize(QtCore.QSize(663, 478))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/AR logo/ARsoftlogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ChatWindow.setWindowIcon(icon)
        ChatWindow.setStyleSheet("")
        self.central_chat = QtWidgets.QWidget(ChatWindow)
        self.central_chat.setObjectName("central_chat")
        self.chatlist = QtWidgets.QLabel(self.central_chat)
        self.chatlist.setGeometry(QtCore.QRect(-5, 0, 241, 41))
        self.chatlist.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 59);\n"
"\n"
"}")
        self.chatlist.setObjectName("chatlist")
        self.clients_field = QtWidgets.QScrollArea(self.central_chat)
        self.clients_field.setGeometry(QtCore.QRect(0, 60, 241, 361))
        self.clients_field.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.clients_field.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.clients_field.setLineWidth(0)
        self.clients_field.setWidgetResizable(True)
        self.clients_field.setObjectName("clients_field")
        self.left_scroll = QtWidgets.QWidget()
        self.left_scroll.setGeometry(QtCore.QRect(0, 0, 241, 361))
        self.left_scroll.setObjectName("left_scroll")
        self.client_info = QtWidgets.QFrame(self.left_scroll)
        self.client_info.setGeometry(QtCore.QRect(1, 2, 236, 60))
        self.client_info.setMinimumSize(QtCore.QSize(236, 60))
        self.client_info.setMaximumSize(QtCore.QSize(236, 60))
        self.client_info.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"")
        self.client_info.setFrameShape(QtWidgets.QFrame.Box)
        self.client_info.setFrameShadow(QtWidgets.QFrame.Plain)
        self.client_info.setLineWidth(1)
        self.client_info.setObjectName("client_info")
        self.msg_countrer = QtWidgets.QLabel(self.client_info)
        self.msg_countrer.setGeometry(QtCore.QRect(184, 18, 22, 22))
        self.msg_countrer.setStyleSheet("QLabel{\n"
"    border-radius:11px;\n"
"    color: rgb(255, 170, 0);\n"
"    background-color: rgb(0, 0, 59);\n"
"}")
        self.msg_countrer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.msg_countrer.setObjectName("msg_countrer")
        self.client_picture = QtWidgets.QLabel(self.client_info)
        self.client_picture.setGeometry(QtCore.QRect(3, 5, 50, 50))
        self.client_picture.setStyleSheet("image:url(:/user_icon/1.png)")
        self.client_picture.setText("")
        self.client_picture.setPixmap(QtGui.QPixmap(":/image/1.png"))
        self.client_picture.setScaledContents(True)
        self.client_picture.setObjectName("client_picture")
        self.online_toast = QtWidgets.QLabel(self.client_info)
        self.online_toast.setGeometry(QtCore.QRect(40, 9, 16, 16))
        self.online_toast.setStyleSheet("QLabel{\n"
"    border-radius:8px;\n"
"    background-color: #00ff00;    \n"
"}")
        self.online_toast.setFrameShadow(QtWidgets.QFrame.Raised)
        self.online_toast.setText("")
        self.online_toast.setObjectName("online_toast")
        self.client_name = QtWidgets.QLabel(self.client_info)
        self.client_name.setGeometry(QtCore.QRect(64, 9, 111, 40))
        self.client_name.setObjectName("client_name")
        self.client_picture.raise_()
        self.msg_countrer.raise_()
        self.online_toast.raise_()
        self.client_name.raise_()
        self.client_info_2 = QtWidgets.QFrame(self.left_scroll)
        self.client_info_2.setGeometry(QtCore.QRect(1, 64, 236, 60))
        self.client_info_2.setMinimumSize(QtCore.QSize(236, 60))
        self.client_info_2.setMaximumSize(QtCore.QSize(236, 60))
        self.client_info_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.client_info_2.setFrameShape(QtWidgets.QFrame.Box)
        self.client_info_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.client_info_2.setLineWidth(1)
        self.client_info_2.setObjectName("client_info_2")
        self.msg_countrer_2 = QtWidgets.QLabel(self.client_info_2)
        self.msg_countrer_2.setGeometry(QtCore.QRect(184, 18, 22, 22))
        self.msg_countrer_2.setStyleSheet("QLabel{\n"
"    border-radius:11px;\n"
"    color: rgb(255, 170, 0);\n"
"    background-color: rgb(0, 0, 59);\n"
"}")
        self.msg_countrer_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.msg_countrer_2.setObjectName("msg_countrer_2")
        self.client_picture_2 = QtWidgets.QLabel(self.client_info_2)
        self.client_picture_2.setGeometry(QtCore.QRect(3, 5, 50, 50))
        self.client_picture_2.setStyleSheet("image:url(:/user_icon/1.png)")
        self.client_picture_2.setText("")
        self.client_picture_2.setPixmap(QtGui.QPixmap(":/image/1.png"))
        self.client_picture_2.setScaledContents(True)
        self.client_picture_2.setObjectName("client_picture_2")
        self.online_toast_2 = QtWidgets.QLabel(self.client_info_2)
        self.online_toast_2.setGeometry(QtCore.QRect(40, 9, 16, 16))
        self.online_toast_2.setStyleSheet("QLabel{\n"
"    border-radius:8px;\n"
"    background-color: #00ff00;    \n"
"}")
        self.online_toast_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.online_toast_2.setText("")
        self.online_toast_2.setObjectName("online_toast_2")
        self.client_name_2 = QtWidgets.QLabel(self.client_info_2)
        self.client_name_2.setGeometry(QtCore.QRect(64, 9, 111, 40))
        self.client_name_2.setObjectName("client_name_2")
        self.clients_field.setWidget(self.left_scroll)
        self.home_button = QtWidgets.QLabel(self.central_chat)
        self.home_button.setGeometry(QtCore.QRect(5, 0, 50, 41))
        self.home_button.setStyleSheet("image: url(:/home_button/2.png);")
        self.home_button.setText("")
        self.home_button.setObjectName("home_button")
        self.active_client = QtWidgets.QLabel(self.central_chat)
        self.active_client.setGeometry(QtCore.QRect(243, 10, 71, 41))
        self.active_client.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 59);\n"
"    border-radius:20px;\n"
"    border:5px solid;\n"
"    border-bottom-color: rgb(255, 170, 0);\n"
"}")
        self.active_client.setObjectName("active_client")
        self.chat_field = QtWidgets.QScrollArea(self.central_chat)
        self.chat_field.setGeometry(QtCore.QRect(251, 47, 401, 291))
        self.chat_field.setStyleSheet("\n"
"QScrollArea{\n"
"    \n"
"    border:1px solid;\n"
"    border-color: rgb(255, 170, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.chat_field.setFrameShape(QtWidgets.QFrame.Box)
        self.chat_field.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.chat_field.setObjectName("chat_field")
        self.right_scroll = QtWidgets.QWidget()
        self.right_scroll.setGeometry(QtCore.QRect(0, 0, 378, 289))
        self.right_scroll.setObjectName("right_scroll")
        self.right_msg_frame = QtWidgets.QFrame(self.right_scroll)
        self.right_msg_frame.setGeometry(QtCore.QRect(0, 90, 381, 101))
        self.right_msg_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_msg_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_msg_frame.setObjectName("r_bubble_container")
        self.layoutWidget = QtWidgets.QWidget(self.right_msg_frame)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 0, 291, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.right_msg_layout = QtWidgets.QGridLayout(self.layoutWidget)
        self.right_msg_layout.setContentsMargins(0, 0, 0, 0)
        self.right_msg_layout.setHorizontalSpacing(2)
        self.right_msg_layout.setVerticalSpacing(3)
        self.right_msg_layout.setObjectName("right_msg_layout")
        self.r_bubble = QtWidgets.QFrame(self.layoutWidget)
        self.r_bubble.setMinimumSize(QtCore.QSize(16, 35))
        self.r_bubble.setMaximumSize(QtCore.QSize(16, 35))
        self.r_bubble.setStyleSheet("background-color: rgb(51, 153, 204);\n"
"border-radius:7px;\n"
"margin-top:1px;\n"
"margin-right:1px;\n"
"margin-bottom:19px;")
        self.r_bubble.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.r_bubble.setFrameShadow(QtWidgets.QFrame.Raised)
        self.r_bubble.setObjectName("r_bubble")
        self.right_msg_layout.addWidget(self.r_bubble, 0, 1, 1, 1)
        self.right_bubble = QtWidgets.QLabel(self.layoutWidget)
        self.right_bubble.setMinimumSize(QtCore.QSize(0, 35))
        self.right_bubble.setMaximumSize(QtCore.QSize(265, 16777215))
        self.right_bubble.setStyleSheet("QLabel{\n"
"    border-radius:15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(51, 153, 204);\n"
"    padding-left:10px;\n"
"    padding-right:10px;\n"
"    padding-top:5px;\n"
"    padding-bottom:5px;\n"
"    line-height:1pt;\n"
"}")
        self.right_bubble.setObjectName("right_bubble")
        self.right_msg_layout.addWidget(self.right_bubble, 0, 0, 1, 1)
        self.right_time = QtWidgets.QLabel(self.layoutWidget)
        self.right_time.setMinimumSize(QtCore.QSize(80, 15))
        self.right_time.setMaximumSize(QtCore.QSize(250, 15))
        self.right_time.setStyleSheet("QLabel{\n"
"    border-radius:7px;\n"
"    color:#000000;\n"
"    background-color: rgb(197, 197, 197);\n"
"    margin-left:56px;\n"
"    margin-right:56px;\n"
"}")
        self.right_time.setObjectName("right_time")
        self.right_msg_layout.addWidget(self.right_time, 1, 0, 1, 1)
        self.left_msg_frame = QtWidgets.QFrame(self.right_scroll)
        self.left_msg_frame.setGeometry(QtCore.QRect(0, 20, 381, 71))
        self.left_msg_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_msg_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_msg_frame.setObjectName("l_bubble_container")
        self.layoutWidget1 = QtWidgets.QWidget(self.left_msg_frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 202, 66))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.left_msg_layout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.left_msg_layout.setContentsMargins(0, 0, 0, 0)
        self.left_msg_layout.setSpacing(2)
        self.left_msg_layout.setObjectName("left_msg_layout")
        self.l_bubble = QtWidgets.QFrame(self.layoutWidget1)
        self.l_bubble.setMinimumSize(QtCore.QSize(16, 35))
        self.l_bubble.setMaximumSize(QtCore.QSize(16, 35))
        self.l_bubble.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-radius:7px;\n"
"margin-top:1px;\n"
"margin-left:1px;\n"
"margin-bottom:19px;")
        self.l_bubble.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.l_bubble.setFrameShadow(QtWidgets.QFrame.Raised)
        self.l_bubble.setObjectName("l_bubble")
        self.left_msg_layout.addWidget(self.l_bubble, 0, 0, 1, 1)
        self.left_time = QtWidgets.QLabel(self.layoutWidget1)
        self.left_time.setMinimumSize(QtCore.QSize(80, 15))
        self.left_time.setMaximumSize(QtCore.QSize(250, 15))
        self.left_time.setStyleSheet("QLabel{\n"
"    border-radius:7px;\n"
"    color:#000000;\n"
"    background-color: rgb(197, 197, 197);\n"
"    margin-left:56px;\n"
"    margin-right:56px;\n"
"}")
        self.left_time.setObjectName("left_time")
        self.left_msg_layout.addWidget(self.left_time, 1, 1, 1, 1)
        self.left_bubble = QtWidgets.QLabel(self.layoutWidget1)
        self.left_bubble.setMinimumSize(QtCore.QSize(0, 35))
        self.left_bubble.setMaximumSize(QtCore.QSize(250, 16777215))
        self.left_bubble.setStyleSheet("QLabel{\n"
"    border-radius:15px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 170, 0);\n"
"    padding-left:10px;    \n"
"    padding-right:10px;\n"
"    padding-top:5px;\n"
"    padding-bottom:5px;\n"
"}")
        self.left_bubble.setObjectName("left_bubble")
        self.left_msg_layout.addWidget(self.left_bubble, 0, 1, 1, 1)
        self.right_msg_frame_2 = QtWidgets.QFrame(self.right_scroll)
        self.right_msg_frame_2.setGeometry(QtCore.QRect(0, 200, 381, 101))
        self.right_msg_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_msg_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_msg_frame_2.setObjectName("right_msg_frame_2")
        self.layoutWidget_3 = QtWidgets.QWidget(self.right_msg_frame_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(90, 0, 291, 101))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.right_msg_layout_3 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.right_msg_layout_3.setContentsMargins(0, 0, 0, 0)
        self.right_msg_layout_3.setHorizontalSpacing(2)
        self.right_msg_layout_3.setVerticalSpacing(3)
        self.right_msg_layout_3.setObjectName("right_msg_layout_3")
        self.r_bubble_3 = QtWidgets.QFrame(self.layoutWidget_3)
        self.r_bubble_3.setMinimumSize(QtCore.QSize(16, 35))
        self.r_bubble_3.setMaximumSize(QtCore.QSize(16, 35))
        self.r_bubble_3.setStyleSheet("background-color: rgb(51, 153, 204);\n"
"border-radius:7px;\n"
"margin-top:1px;\n"
"margin-right:1px;\n"
"margin-bottom:19px;")
        self.r_bubble_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.r_bubble_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.r_bubble_3.setObjectName("r_bubble_3")
        self.right_msg_layout_3.addWidget(self.r_bubble_3, 0, 1, 1, 1)
        self.right_bubble_3 = QtWidgets.QLabel(self.layoutWidget_3)
        self.right_bubble_3.setMinimumSize(QtCore.QSize(0, 35))
        self.right_bubble_3.setMaximumSize(QtCore.QSize(265, 16777215))
        self.right_bubble_3.setStyleSheet("QLabel{\n"
"    border-radius:15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(51, 153, 204);\n"
"    padding-left:10px;\n"
"    padding-right:10px;\n"
"    padding-top:5px;\n"
"    padding-bottom:5px;\n"
"    line-height:1pt;\n"
"}")
        self.right_bubble_3.setObjectName("right_bubble_3")
        self.right_msg_layout_3.addWidget(self.right_bubble_3, 0, 0, 1, 1)
        self.right_time_3 = QtWidgets.QLabel(self.layoutWidget_3)
        self.right_time_3.setMinimumSize(QtCore.QSize(80, 15))
        self.right_time_3.setMaximumSize(QtCore.QSize(250, 15))
        self.right_time_3.setStyleSheet("QLabel{\n"
"    border-radius:7px;\n"
"    color:#000000;\n"
"    background-color: rgb(197, 197, 197);\n"
"    margin-left:56px;\n"
"    margin-right:56px;\n"
"}")
        self.right_time_3.setObjectName("right_time_3")
        self.right_msg_layout_3.addWidget(self.right_time_3, 1, 0, 1, 1)
        self.right_msg_frame_3 = QtWidgets.QFrame(self.right_msg_frame_2)
        self.right_msg_frame_3.setGeometry(QtCore.QRect(0, 120, 381, 101))
        self.right_msg_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_msg_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_msg_frame_3.setObjectName("right_msg_frame_3")
        self.layoutWidget_4 = QtWidgets.QWidget(self.right_msg_frame_3)
        self.layoutWidget_4.setGeometry(QtCore.QRect(90, 0, 291, 101))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.right_msg_layout_4 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.right_msg_layout_4.setContentsMargins(0, 0, 0, 0)
        self.right_msg_layout_4.setHorizontalSpacing(2)
        self.right_msg_layout_4.setVerticalSpacing(3)
        self.right_msg_layout_4.setObjectName("right_msg_layout_4")
        self.r_bubble_4 = QtWidgets.QFrame(self.layoutWidget_4)
        self.r_bubble_4.setMinimumSize(QtCore.QSize(16, 35))
        self.r_bubble_4.setMaximumSize(QtCore.QSize(16, 35))
        self.r_bubble_4.setStyleSheet("background-color: rgb(51, 153, 204);\n"
"border-radius:7px;\n"
"margin-top:1px;\n"
"margin-right:1px;\n"
"margin-bottom:19px;")
        self.r_bubble_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.r_bubble_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.r_bubble_4.setObjectName("r_bubble_4")
        self.right_msg_layout_4.addWidget(self.r_bubble_4, 0, 1, 1, 1)
        self.right_bubble_4 = QtWidgets.QLabel(self.layoutWidget_4)
        self.right_bubble_4.setMinimumSize(QtCore.QSize(0, 35))
        self.right_bubble_4.setMaximumSize(QtCore.QSize(265, 16777215))
        self.right_bubble_4.setStyleSheet("QLabel{\n"
"    border-radius:15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(51, 153, 204);\n"
"    padding-left:10px;\n"
"    padding-right:10px;\n"
"    padding-top:5px;\n"
"    padding-bottom:5px;\n"
"    line-height:1pt;\n"
"}")
        self.right_bubble_4.setObjectName("right_bubble_4")
        self.right_msg_layout_4.addWidget(self.right_bubble_4, 0, 0, 1, 1)
        self.right_time_4 = QtWidgets.QLabel(self.layoutWidget_4)
        self.right_time_4.setMinimumSize(QtCore.QSize(80, 15))
        self.right_time_4.setMaximumSize(QtCore.QSize(250, 15))
        self.right_time_4.setStyleSheet("QLabel{\n"
"    border-radius:7px;\n"
"    color:#000000;\n"
"    background-color: rgb(197, 197, 197);\n"
"    margin-left:56px;\n"
"    margin-right:56px;\n"
"}")
        self.right_time_4.setObjectName("right_time_4")
        self.right_msg_layout_4.addWidget(self.right_time_4, 1, 0, 1, 1)
        self.chat_field.setWidget(self.right_scroll)
        self.media_bg = QtWidgets.QFrame(self.central_chat)
        self.media_bg.setGeometry(QtCore.QRect(300, 350, 211, 41))
        self.media_bg.setStyleSheet("QFrame{\n"
"    border-radius:20px;\n"
"    background-color: rgba(90, 162, 255, 90);\n"
"}")
        self.media_bg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.media_bg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.media_bg.setObjectName("media_bg")
        self.widget = QtWidgets.QWidget(self.media_bg)
        self.widget.setGeometry(QtCore.QRect(11, 1, 180, 42))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.media_image = QtWidgets.QLabel(self.widget)
        self.media_image.setMinimumSize(QtCore.QSize(40, 40))
        self.media_image.setMaximumSize(QtCore.QSize(16777215, 40))
        self.media_image.setStyleSheet("image: url(:/image_button/photo.png);")
        self.media_image.setText("")
        self.media_image.setObjectName("media_image")
        self.horizontalLayout.addWidget(self.media_image)
        self.media_music = QtWidgets.QLabel(self.widget)
        self.media_music.setMinimumSize(QtCore.QSize(40, 40))
        self.media_music.setMaximumSize(QtCore.QSize(16777215, 40))
        self.media_music.setStyleSheet("image: url(:/audio_button/song.png);")
        self.media_music.setText("")
        self.media_music.setObjectName("media_music")
        self.horizontalLayout.addWidget(self.media_music)
        self.media_video = QtWidgets.QLabel(self.widget)
        self.media_video.setMinimumSize(QtCore.QSize(40, 40))
        self.media_video.setMaximumSize(QtCore.QSize(16777215, 40))
        self.media_video.setStyleSheet("image:url(:/video_button/video.png);")
        self.media_video.setText("")
        self.media_video.setObjectName("media_video")
        self.horizontalLayout.addWidget(self.media_video)
        self.media_doc = QtWidgets.QLabel(self.widget)
        self.media_doc.setMinimumSize(QtCore.QSize(40, 40))
        self.media_doc.setMaximumSize(QtCore.QSize(16777215, 40))
        self.media_doc.setStyleSheet("image: url(:/doc_button/document.png);")
        self.media_doc.setText("")
        self.media_doc.setObjectName("media_doc")
        self.horizontalLayout.addWidget(self.media_doc)
        self.left_bg = QtWidgets.QFrame(self.central_chat)
        self.left_bg.setGeometry(QtCore.QRect(-1, 0, 238, 431))
        self.left_bg.setStyleSheet("background-color: rgba(24, 53, 72, 250);")
        self.left_bg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_bg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_bg.setObjectName("left_bg")
        self.active_client_bg = QtWidgets.QLabel(self.central_chat)
        self.active_client_bg.setGeometry(QtCore.QRect(237, -4, 451, 51))
        self.active_client_bg.setStyleSheet("background-color: rgba(255, 255, 255, 255);\n"
"image: url(:/multilogo/multilog.png);\n"
"")
        self.active_client_bg.setText("")
        self.active_client_bg.setScaledContents(True)
        self.active_client_bg.setObjectName("active_client_bg")
        self.delete_button = QtWidgets.QLabel(self.central_chat)
        self.delete_button.setGeometry(QtCore.QRect(625, 17, 41, 31))
        self.delete_button.setStyleSheet("image: url(:/delete_button/24778-200.png);")
        self.delete_button.setText("")
        self.delete_button.setObjectName("delete_button")
        self.connect_button = QtWidgets.QPushButton(self.central_chat)
        self.connect_button.setGeometry(QtCore.QRect(516, 13, 111, 31))
        self.connect_button.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.connect_button.setObjectName("connect_button")
        self.media_button = QtWidgets.QLabel(self.central_chat)
        self.media_button.setGeometry(QtCore.QRect(251, 385, 40, 40))
        self.media_button.setMinimumSize(QtCore.QSize(40, 40))
        self.media_button.setMaximumSize(QtCore.QSize(40, 40))
        self.media_button.setStyleSheet("")
        self.media_button.setPixmap(QtGui.QPixmap(":/plus_button/More.png"))
        self.media_button.setScaledContents(False)
        self.media_button.setAlignment(QtCore.Qt.AlignCenter)
        self.media_button.setObjectName("media_button")

        self.entry_field = QtWidgets.QLineEdit(self.central_chat)
        self.entry_field.setGeometry(QtCore.QRect(297, 385, 310, 40))
        self.entry_field.setMinimumSize(QtCore.QSize(310, 40))
        self.entry_field.setMaximumSize(QtCore.QSize(310, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.entry_field.setFont(font)
        self.entry_field.setStyleSheet("QLineEdit{\n"
"    border:1px solid;\n"
"    padding-left:10px;\n"
"    padding-right:10px;\n"
"    border-color: rgb(0, 85, 255);\n"
"    border-radius:18px;\n"
"}")
        self.entry_field.setFrame(True)
        self.entry_field.setObjectName("entry_field")
        self.send_button = QtWidgets.QLabel(self.central_chat)
        self.send_button.setGeometry(QtCore.QRect(613, 385, 40, 40))
        self.send_button.setMinimumSize(QtCore.QSize(40, 40))
        self.send_button.setMaximumSize(QtCore.QSize(40, 40))
        self.send_button.setStyleSheet("")
        self.send_button.setText("")
        self.send_button.setPixmap(QtGui.QPixmap(":/send_button/send.png"))
        self.send_button.setScaledContents(True)
        self.send_button.setObjectName("send_button")
        self.left_bg.raise_()
        self.media_button.raise_()
        self.entry_field.raise_()
        self.send_button.raise_()
        self.active_client_bg.raise_()
        self.chat_field.raise_()
        self.chatlist.raise_()
        self.clients_field.raise_()
        self.home_button.raise_()
        self.delete_button.raise_()
        self.connect_button.raise_()
        self.media_bg.raise_()
        self.active_client.raise_()
        ChatWindow.setCentralWidget(self.central_chat)
        self.menubar = QtWidgets.QMenuBar(ChatWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 663, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        ChatWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChatWindow)
        self.statusbar.setWindowTitle()
        self.statusbar.setObjectName("statusbar")
        ChatWindow.setStatusBar(self.statusbar)
        self.actionAide = QtWidgets.QAction(ChatWindow)
        self.actionAide.setObjectName("actionAide")
        self.actionQuitter = QtWidgets.QAction(ChatWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.menuMenu.addAction(self.actionAide)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionQuitter)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(ChatWindow)
        QtCore.QMetaObject.connectSlotsByName(ChatWindow)
        ChatWindow.setTabOrder(self.clients_field, self.entry_field)
        ChatWindow.setTabOrder(self.entry_field, self.chat_field)
        ChatWindow.setTabOrder(self.chat_field, self.connect_button)

    def retranslateUi(self, ChatWindow):
        _translate = QtCore.QCoreApplication.translate
        ChatWindow.setWindowTitle(_translate("ChatWindow", "AR Intercom"))
        self.chatlist.setText(_translate("ChatWindow", "<p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Chat list</span></p>"))
        self.msg_countrer.setText(_translate("ChatWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">3</span></p></body></html>"))
        self.client_name.setText(_translate("ChatWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">AlphaBravo</span></p></body></html>"))
        self.msg_countrer_2.setText(_translate("ChatWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">3</span></p></body></html>"))
        self.client_name_2.setText(_translate("ChatWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">AlphaBravo</span></p></body></html>"))
        self.active_client.setText(_translate("ChatWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Delta</span></p></body></html>"))
        self.right_bubble.setText(_translate("ChatWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Message envoyé ici. mais un peu</span></p><p><span style=\" font-size:10pt;\">plus slong que d\'habitude</span></p></body></html>"))
        self.right_time.setText(_translate("ChatWindow", "<p align=\"center\"><span style=\" font-size:6pt;\">28-03-21 14:03</span></p>"))
        self.left_time.setText(_translate("ChatWindow", "<p align=\"center\"><span style=\" font-size:6pt;\">28-03-21 14:03</span></p>"))
        self.left_bubble.setText(_translate("ChatWindow", "<p><span style=\" font-size:10pt;\">Message reçu ici.</span></p>"))
        self.right_bubble_3.setText(_translate("ChatWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Message envoyé ici. mais un peu</span></p><p><span style=\" font-size:10pt;\">plus slong que d\'habitude</span></p></body></html>"))
        self.right_time_3.setText(_translate("ChatWindow", "<p align=\"center\"><span style=\" font-size:6pt;\">28-03-21 14:03</span></p>"))
        self.right_bubble_4.setText(_translate("ChatWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Message envoyé ici. mais un peu</span></p><p><span style=\" font-size:10pt;\">plus slong que d\'habitude</span></p></body></html>"))
        self.right_time_4.setText(_translate("ChatWindow", "<p align=\"center\"><span style=\" font-size:6pt;\">28-03-21 14:03</span></p>"))
        self.connect_button.setText(_translate("ChatWindow", "Connecter"))
        self.entry_field.setPlaceholderText(_translate("ChatWindow", "Saisissez votre message ici !"))
        self.menuMenu.setTitle(_translate("ChatWindow", "Menu"))
        self.actionAide.setText(_translate("ChatWindow", "Aide"))
        self.actionQuitter.setText(_translate("ChatWindow", "Quitter"))
import user_profile_picture_rc
