# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'medias.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 411)
        MainWindow.setStyleSheet("background-color: rgb(85, 85, 127);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(430, 40, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.arv_bubble = QtWidgets.QFrame(self.centralwidget)
        self.arv_bubble.setGeometry(QtCore.QRect(20, 20, 301, 70))
        self.arv_bubble.setStyleSheet("QFrame{\n"
"    background-color:#88FFFFFF;\n"
"    border-radius:10px;\n"
"\n"
"}")
        self.arv_bubble.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.arv_bubble.setFrameShadow(QtWidgets.QFrame.Raised)
        self.arv_bubble.setObjectName("arv_bubble")
        self.title = QtWidgets.QLabel(self.arv_bubble)
        self.title.setGeometry(QtCore.QRect(52, 3, 241, 20))
        self.title.setStyleSheet("QLabel{\n"
"    background:#44FFFFFF;\n"
"}")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.elapsed_time = QtWidgets.QLabel(self.arv_bubble)
        self.elapsed_time.setGeometry(QtCore.QRect(52, 49, 51, 16))
        self.elapsed_time.setStyleSheet("QLabel{\n"
"    background:#22FFFFFF;\n"
"    border-radius:8px;\n"
"}")
        self.elapsed_time.setAlignment(QtCore.Qt.AlignCenter)
        self.elapsed_time.setObjectName("elapsed_time")
        self.total_time = QtWidgets.QLabel(self.arv_bubble)
        self.total_time.setGeometry(QtCore.QRect(241, 49, 51, 16))
        self.total_time.setStyleSheet("QLabel{\n"
"    background:#22FFFFFF;\n"
"    border-radius:8px;\n"
"}")
        self.total_time.setAlignment(QtCore.Qt.AlignCenter)
        self.total_time.setObjectName("total_time")
        self.progress = QtWidgets.QProgressBar(self.arv_bubble)
        self.progress.setGeometry(QtCore.QRect(52, 33, 241, 5))
        self.progress.setStyleSheet("QProgressBar{\n"
"        background-color:#AAC5C5C5;\n"
"        border-radius:2px;\n"
"        border:none;\n"
"        text-align:center;\n"
"}\n"
"\n"
"QProgressBar::chunk{    \n"
"       background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 52, 93, 255), stop:1 rgba(0, 121, 215, 255));\n"
"        border-radius:2px;\n"
"\n"
"}")
        self.progress.setMaximum(100)
        self.progress.setProperty("value", 0)
        self.progress.setTextVisible(False)
        self.progress.setObjectName("progress")
        self.slider = QtWidgets.QSlider(self.arv_bubble)
        self.slider.setGeometry(QtCore.QRect(52, 30, 241, 12))
        self.slider.setStyleSheet("QSlider{\n"
"    background:none;\n"
"}\n"
"\n"
"QSlider::groove{\n"
"    background:none;\n"
"    border:none;}\n"
"\n"
"QSlider::handle{\n"
"    height:12px;\n"
"    width:12px;\n"
"    background-color: rgb(0, 121, 215, 255);\n"
"    border-radius:6px;}\n"
"\n"
"QSlider::handle:hover{\n"
"    background-color: rgb(0, 52, 93, 255);}\n"
"\n"
"QSlider::handle:pressed{\n"
"    background-color: rgb(0, 121, 215, 255);}")
        self.slider.setMaximum(100)
        self.slider.setProperty("value", 0)
        self.slider.setSliderPosition(0)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.play_button = QtWidgets.QPushButton(self.arv_bubble)
        self.play_button.setGeometry(QtCore.QRect(7, 16, 41, 41))
        self.play_button.setStyleSheet("QPushButton{\n"
"    background-image: url(:/cils/cils/cil-media-play.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position:center;\n"
"    border-radius:6px;\n"
"    border:none;\n"
"}")
        self.play_button.setObjectName("play_button")
        self.record_tip = QtWidgets.QFrame(self.centralwidget)
        self.record_tip.setGeometry(QtCore.QRect(20, 110, 161, 31))
        self.record_tip.setStyleSheet("QFrame{\n"
"    background-color:#88FFFFFF;\n"
"    border-radius:15px;\n"
"\n"
"}")
        self.record_tip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.record_tip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.record_tip.setObjectName("record_tip")
        self.record_time = QtWidgets.QLabel(self.record_tip)
        self.record_time.setGeometry(QtCore.QRect(45, 5, 71, 20))
        self.record_time.setStyleSheet("QLabel{\n"
"    background:#44FFFFFF;\n"
"    border-radius:none;\n"
"}")
        self.record_time.setAlignment(QtCore.Qt.AlignCenter)
        self.record_time.setObjectName("record_time")
        self.end_record = QtWidgets.QPushButton(self.record_tip)
        self.end_record.setGeometry(QtCore.QRect(10, 5, 31, 20))
        self.end_record.setStyleSheet("QPushButton{\n"
"    background:#4400FF00;\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"}")
        self.end_record.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/control.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.end_record.setIcon(icon)
        self.end_record.setIconSize(QtCore.QSize(50, 50))
        self.end_record.setObjectName("end_record")
        self.cancel_record = QtWidgets.QPushButton(self.record_tip)
        self.cancel_record.setGeometry(QtCore.QRect(119, 5, 31, 20))
        self.cancel_record.setStyleSheet("QPushButton{\n"
"    background:#44FF0000;\n"
"    border-top-right-radius:10px;\n"
"    border-bottom-right-radius:10px;\n"
"}")
        self.cancel_record.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/control-stop-square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_record.setIcon(icon1)
        self.cancel_record.setIconSize(QtCore.QSize(50, 50))
        self.cancel_record.setObjectName("cancel_record")
        self.arv_bubble_2 = QtWidgets.QFrame(self.centralwidget)
        self.arv_bubble_2.setGeometry(QtCore.QRect(40, 220, 311, 81))
        self.arv_bubble_2.setStyleSheet("QFrame{\n"
"    background-color:#88FFFFFF;\n"
"    border-radius:10px;\n"
"\n"
"}")
        self.arv_bubble_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.arv_bubble_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.arv_bubble_2.setObjectName("arv_bubble_2")
        self.elapsed_time_2 = QtWidgets.QLabel(self.arv_bubble_2)
        self.elapsed_time_2.setGeometry(QtCore.QRect(80, 10, 231, 16))
        self.elapsed_time_2.setStyleSheet("QLabel{\n"
"    background:none;\n"
"}")
        self.elapsed_time_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.elapsed_time_2.setObjectName("elapsed_time_2")
        self.play_button_2 = QtWidgets.QPushButton(self.arv_bubble_2)
        self.play_button_2.setGeometry(QtCore.QRect(7, 16, 61, 61))
        self.play_button_2.setStyleSheet("QPushButton{\n"
"    image: url(:/icons/icons/AR_logo.png);\n"
"    background:none;\n"
"    border:none;\n"
"}")
        self.play_button_2.setObjectName("play_button_2")
        self.elapsed_time_3 = QtWidgets.QLabel(self.arv_bubble_2)
        self.elapsed_time_3.setGeometry(QtCore.QRect(80, 40, 231, 16))
        self.elapsed_time_3.setStyleSheet("QLabel{\n"
"    background:none;\n"
"}")
        self.elapsed_time_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.elapsed_time_3.setObjectName("elapsed_time_3")
        self.elapsed_time_4 = QtWidgets.QLabel(self.arv_bubble_2)
        self.elapsed_time_4.setGeometry(QtCore.QRect(80, 60, 231, 16))
        self.elapsed_time_4.setStyleSheet("QLabel{\n"
"    background:none;\n"
"}")
        self.elapsed_time_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.elapsed_time_4.setObjectName("elapsed_time_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 722, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.slider.sliderMoved['int'].connect(self.progress.setValue)
        self.progress.valueChanged['int'].connect(self.slider.setValue)
        self.progress.valueChanged['int'].connect(self.label_3.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "0"))
        self.title.setText(_translate("MainWindow", "ARV-20062021-1200"))
        self.elapsed_time.setText(_translate("MainWindow", "00:00"))
        self.total_time.setText(_translate("MainWindow", "00:00"))
        self.record_time.setText(_translate("MainWindow", "00:00"))
        self.elapsed_time_2.setText(_translate("MainWindow", "Nouveau message"))
        self.elapsed_time_3.setText(_translate("MainWindow", "Un message de Antares"))
        self.elapsed_time_4.setText(_translate("MainWindow", "AR Intercom"))
import img_rc
