# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signinwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SigninWindow(object):
    def setupUi(self, SigninWindow):
        SigninWindow.setObjectName("SigninWindow")
        SigninWindow.resize(275, 661)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-user-follow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SigninWindow.setWindowIcon(icon)
        self.stackedWidget = QtWidgets.QStackedWidget(SigninWindow)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 45, 275, 611))
        self.stackedWidget.setStyleSheet("QStackedWidget{\n"
"    background-color:#FFFFFF;\n"
"    border-bottom-left-radius:12px;\n"
"    border-bottom-right-radius:12px;\n"
"}\n"
"\n"
"\n"
"/* SCROLL BAR */\n"
"            \n"
"QScrollBar:vertical{border: none;background: #CCDDFF;width: 10px; margin: 21px 0 21px 0; border-radius: 0px;}\n"
"\n"
"QScrollBar::handle:vertical{background: #3385CC; min-height: 25px; border-radius: 5px;}\n"
"\n"
"QScrollBar::add-line:vertical{border: none; background: #3385CC;height: 20px;\n"
"            border-bottom-left-radius: 5px; border-bottom-right-radius: 5px;\n"
"            subcontrol-position: bottom; subcontrol-origin: margin;}\n"
"\n"
"QScrollBar::sub-line:vertical{border: none; background: #3385CC; height: 20px;\n"
"            border-top-left-radius: 5px; border-top-right-radius: 5px;\n"
"            subcontrol-position: top;subcontrol-origin: margin;}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical{background: none;}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {background: none;}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("")
        self.page.setObjectName("page")
        self.central_signin = QtWidgets.QFrame(self.page)
        self.central_signin.setGeometry(QtCore.QRect(0, 0, 275, 601))
        self.central_signin.setMinimumSize(QtCore.QSize(275, 511))
        self.central_signin.setMaximumSize(QtCore.QSize(275, 16777215))
        self.central_signin.setStyleSheet("")
        self.central_signin.setObjectName("central_signin")
        self.create_account = QtWidgets.QLabel(self.central_signin)
        self.create_account.setGeometry(QtCore.QRect(-2, 30, 280, 21))
        self.create_account.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);font-size:14px; font-family:Roboto ;\n"
"border-radius:10px;")
        self.create_account.setAlignment(QtCore.Qt.AlignCenter)
        self.create_account.setObjectName("create_account")
        self.form = QtWidgets.QFrame(self.central_signin)
        self.form.setGeometry(QtCore.QRect(2, 138, 271, 241))
        self.form.setStyleSheet("QFrame{\n"
"background-color: rgba(57, 146, 240, 50);\n"
"border-radius:20px;}")
        self.form.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.form.setFrameShadow(QtWidgets.QFrame.Raised)
        self.form.setObjectName("form")
        self.user_name = QtWidgets.QLineEdit(self.form)
        self.user_name.setGeometry(QtCore.QRect(10, 10, 250, 40))
        self.user_name.setStyleSheet("QLineEdit{\n"
"    border:2px solid; \n"
"    border-radius:20px;\n"
"    font-size:18px;\n"
"    padding-left:15px;\n"
"    padding-right:15px; \n"
"    border-color:#FFF; \n"
"    background-color:#FFFFFF;}\n"
"\n"
"QLineEdit:hover,  QLineEdit:focus{\n"
"    border-color: rgba(57, 146, 240, 180); \n"
"}")
        self.user_name.setObjectName("user_name")
        self.code = QtWidgets.QComboBox(self.form)
        self.code.setGeometry(QtCore.QRect(10, 67, 250, 40))
        self.code.setStyleSheet("QComboBox{\n"
"    border:2px solid #FFF; \n"
"    border-radius:20px;\n"
"    font-size:18px;\n"
"    padding-left:15px;\n"
"    padding-right:15px; \n"
"    background-color:#FFFFFF;\n"
"    color:#80000000;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px;\n"
"    border-left-width: 2px;\n"
"    border-left-style: solid;\n"
"    border-left-color: rgba(57, 146, 240, 180);\n"
"    border-top-right-radius: 2px;\n"
"    border-bottom-right-radius: 3px;\n"
"    background-image: url(:cils/cils/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"}\n"
"\n"
"QComboBox:hover, QComboBox:focus{\n"
"    border-color: rgba(57, 146, 240, 180);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color:#000;\n"
"    background-color:#FFF;\n"
"    padding: 10px;\n"
"    selection-color:#3385CC;\n"
"    selection-background-color:#10000000;\n"
"}\n"
"\n"
"\n"
"/* SCROLL BAR */\n"
"            \n"
"QScrollBar:vertical{border: none;background: #CCDDFF;width: 10px; margin: 11px 0 11px 0; border-radius: 0px;}\n"
"\n"
"QScrollBar::handle:vertical{background: #3385CC; min-height: 25px; border-radius: 5px;}\n"
"\n"
"QScrollBar::add-line:vertical{border: none; background: #3385CC;height: 10px;\n"
"            border-bottom-left-radius: 5px; border-bottom-right-radius: 5px;\n"
"            subcontrol-position: bottom; subcontrol-origin: margin;}\n"
"\n"
"QScrollBar::sub-line:vertical{border: none; background: #3385CC; height: 10px;\n"
"            border-top-left-radius: 5px; border-top-right-radius: 5px;\n"
"            subcontrol-position: top;subcontrol-origin: margin;}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical{background: none;}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {background: none;}")
        self.code.setMaxVisibleItems(4)
        self.code.setFrame(False)
        self.code.setObjectName("code")
        self.code.addItem("")
        self.code.setItemText(0, "Nom de code")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.passcode = QtWidgets.QLineEdit(self.form)
        self.passcode.setGeometry(QtCore.QRect(10, 121, 250, 40))
        self.passcode.setStyleSheet("QLineEdit{\n"
"    border:2px solid; \n"
"    border-radius:20px;\n"
"    font-size:18px;\n"
"    padding-left:15px;\n"
"    padding-right:15px; \n"
"    border-color:#FFF; \n"
"    background-color:#FFFFFF;}\n"
"\n"
"QLineEdit:hover,  QLineEdit:focus{\n"
"    border-color: rgba(57, 146, 240, 180); \n"
"}")
        self.passcode.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.passcode.setObjectName("passcode")
        self.passcode2 = QtWidgets.QLineEdit(self.form)
        self.passcode2.setGeometry(QtCore.QRect(10, 180, 250, 40))
        self.passcode2.setStyleSheet("QLineEdit{\n"
"    border:2px solid; \n"
"    border-radius:20px;\n"
"    font-size:18px;\n"
"    padding-left:15px;\n"
"    padding-right:15px; \n"
"    border-color:#FFF; \n"
"    background-color:#FFFFFF;}\n"
"\n"
"QLineEdit:hover,  QLineEdit:focus{\n"
"    border-color: rgba(57, 146, 240, 180); \n"
"}")
        self.passcode2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passcode2.setObjectName("passcode2")
        self.code.raise_()
        self.user_name.raise_()
        self.passcode.raise_()
        self.passcode2.raise_()
        self.logo = QtWidgets.QLabel(self.central_signin)
        self.logo.setGeometry(QtCore.QRect(0, 59, 271, 71))
        self.logo.setStyleSheet("background-color: rgba(57, 146, 240, 5);\n"
"background-image: url(:/icons/icons/multilogo.png);\n"
"image:url(:/icons/icons/ARsoftlogo.png)")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.welcome = QtWidgets.QLabel(self.central_signin)
        self.welcome.setGeometry(QtCore.QRect(0, 1, 281, 41))
        self.welcome.setStyleSheet("background-color: rgb(51, 153, 204);\n"
"color: rgb(255, 255, 255);font-size:16px; font-weight:bold; font-family:Roboto ;")
        self.welcome.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.welcome.setObjectName("welcome")
        self.image_field = QtWidgets.QFrame(self.central_signin)
        self.image_field.setGeometry(QtCore.QRect(2, 386, 270, 141))
        self.image_field.setStyleSheet("QFrame{\n"
"background-color: rgba(57, 146, 240, 50);\n"
"border-radius:20px;\n"
"}")
        self.image_field.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.image_field.setFrameShadow(QtWidgets.QFrame.Raised)
        self.image_field.setObjectName("image_field")
        self.choose_profilepicture = QtWidgets.QLabel(self.image_field)
        self.choose_profilepicture.setGeometry(QtCore.QRect(64, 5, 131, 131))
        self.choose_profilepicture.setStyleSheet("QLabel{\n"
"    border:1px solid #FFF;\n"
"    border-radius:65px;\n"
"    font-size:12px;\n"
"    padding-left:15px;\n"
"    padding-right:15px; \n"
"    background-color:#FFFFFF;\n"
"    background-image: url(:/cils/cils/cil-user.png);    \n"
"    background-position:center;\n"
"    background-repeat:no-repeat;\n"
"\n"
"}\n"
"\n"
"QLabel:hover,  QFrame:focus{\n"
"    border-color: rgba(57, 146, 240, 180); \n"
"}")
        self.choose_profilepicture.setScaledContents(True)
        self.choose_profilepicture.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.choose_profilepicture.setObjectName("choose_profilepicture")
        self.next = QtWidgets.QPushButton(self.central_signin)
        self.next.setGeometry(QtCore.QRect(70, 554, 131, 41))
        self.next.setStyleSheet("QPushButton{\n"
"    border:none; \n"
"    border-radius:20px; \n"
"    font-size:18px; \n"
"    font-weight:bold;\n"
"    padding-left:15px;\n"
"    padding-right:15px; \n"
"    background-color:rgba(57, 146, 240, 180);\n"
"    color:#FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border:2px solid rgba(57, 146, 240, 250); \n"
"    font-weight:0;\n"
"    background-color:#FFFFFF;\n"
"    color:rgba(57, 146, 240, 250);\n"
"}")
        self.next.setObjectName("next")
        self.logo.raise_()
        self.form.raise_()
        self.welcome.raise_()
        self.create_account.raise_()
        self.image_field.raise_()
        self.next.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.central_signin_2 = QtWidgets.QFrame(self.page_2)
        self.central_signin_2.setGeometry(QtCore.QRect(0, 1, 275, 601))
        self.central_signin_2.setMinimumSize(QtCore.QSize(275, 511))
        self.central_signin_2.setMaximumSize(QtCore.QSize(275, 16777215))
        self.central_signin_2.setStyleSheet("outline:none;")
        self.central_signin_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.central_signin_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.central_signin_2.setObjectName("central_signin_2")
        self.read_carefuly = QtWidgets.QLabel(self.central_signin_2)
        self.read_carefuly.setGeometry(QtCore.QRect(0, 28, 275, 21))
        self.read_carefuly.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);font-size:14px; font-family:Roboto ;\n"
"border-radius:10px;")
        self.read_carefuly.setAlignment(QtCore.Qt.AlignCenter)
        self.read_carefuly.setObjectName("read_carefuly")
        self.logo_2 = QtWidgets.QLabel(self.central_signin_2)
        self.logo_2.setGeometry(QtCore.QRect(0, 57, 271, 71))
        self.logo_2.setStyleSheet("background-color: rgba(57, 146, 240, 5);\n"
"background-image: url(:/icons/icons/multilogo.png);\n"
"image:url(:/icons/icons/ARsoftlogo.png)")
        self.logo_2.setText("")
        self.logo_2.setObjectName("logo_2")
        self.cgu = QtWidgets.QLabel(self.central_signin_2)
        self.cgu.setGeometry(QtCore.QRect(0, 0, 280, 41))
        self.cgu.setStyleSheet("background-color: rgb(51, 153, 204);\n"
"color: rgb(255, 255, 255);font-size:16px; font-weight:bold; font-family:Roboto ;")
        self.cgu.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.cgu.setObjectName("cgu")
        self.validate = QtWidgets.QPushButton(self.central_signin_2)
        self.validate.setGeometry(QtCore.QRect(70, 554, 131, 41))
        self.validate.setStyleSheet("QPushButton{\n"
"    border:none; \n"
"    border-radius:20px; \n"
"    font-size:18px; \n"
"    font-weight:bold;\n"
"    padding-left:15px;\n"
"    padding-right:15px; \n"
"    background-color:rgba(57, 146, 240, 180);\n"
"    color:#FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border:2px solid rgba(57, 146, 240, 250); \n"
"    font-weight:0;\n"
"    background-color:#FFFFFF;\n"
"    color:rgba(57, 146, 240, 250);\n"
"}")
        self.validate.setObjectName("validate")
        self.textBrowser = QtWidgets.QTextBrowser(self.central_signin_2)
        self.textBrowser.setGeometry(QtCore.QRect(3, 132, 270, 371))
        self.textBrowser.setStyleSheet("QTextBrowser{\n"
"    border-top-right-radius:5px;\n"
"    border-bottom-right-radius:5px;\n"
"    font-size:16px;\n"
"}")
        self.textBrowser.setObjectName("textBrowser")
        self.iaggree = QtWidgets.QCheckBox(self.central_signin_2)
        self.iaggree.setGeometry(QtCore.QRect(10, 522, 261, 20))
        self.iaggree.setObjectName("iaggree")
        self.logo_2.raise_()
        self.cgu.raise_()
        self.read_carefuly.raise_()
        self.validate.raise_()
        self.textBrowser.raise_()
        self.iaggree.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.cgu_2 = QtWidgets.QLabel(self.page_3)
        self.cgu_2.setGeometry(QtCore.QRect(0, 2, 280, 41))
        self.cgu_2.setStyleSheet("background-color: rgb(51, 153, 204);\n"
"color: rgb(255, 255, 255);font-size:16px; font-weight:bold; font-family:Roboto ;")
        self.cgu_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.cgu_2.setObjectName("cgu_2")
        self.read_carefuly_2 = QtWidgets.QLabel(self.page_3)
        self.read_carefuly_2.setGeometry(QtCore.QRect(0, 30, 275, 21))
        self.read_carefuly_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);font-size:14px; font-family:Roboto ;\n"
"border-radius:10px;")
        self.read_carefuly_2.setAlignment(QtCore.Qt.AlignCenter)
        self.read_carefuly_2.setObjectName("read_carefuly_2")
        self.whatnews_frame = QtWidgets.QFrame(self.page_3)
        self.whatnews_frame.setGeometry(QtCore.QRect(0, 50, 275, 556))
        self.whatnews_frame.setStyleSheet("")
        self.whatnews_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.whatnews_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.whatnews_frame.setObjectName("whatnews_frame")
        self.what_isnew = QtWidgets.QStackedWidget(self.whatnews_frame)
        self.what_isnew.setGeometry(QtCore.QRect(2, 0, 270, 491))
        self.what_isnew.setStyleSheet("background-color: #FFFFFF;")
        self.what_isnew.setObjectName("what_isnew")
        self.w0 = QtWidgets.QWidget()
        self.w0.setStyleSheet("image: url(:/features/Features/0.png);")
        self.w0.setObjectName("w0")
        self.what_isnew.addWidget(self.w0)
        self.w1 = QtWidgets.QWidget()
        self.w1.setStyleSheet("image: url(:/features/Features/1.png);")
        self.w1.setObjectName("w1")
        self.what_isnew.addWidget(self.w1)
        self.w2 = QtWidgets.QWidget()
        self.w2.setStyleSheet("image: url(:/features/Features/2.png);")
        self.w2.setObjectName("w2")
        self.what_isnew.addWidget(self.w2)
        self.w3 = QtWidgets.QWidget()
        self.w3.setStyleSheet("image: url(:/features/Features/3.png);")
        self.w3.setObjectName("w3")
        self.what_isnew.addWidget(self.w3)
        self.w4 = QtWidgets.QWidget()
        self.w4.setStyleSheet("image: url(:/features/Features/4.png);")
        self.w4.setObjectName("w4")
        self.what_isnew.addWidget(self.w4)
        self.w5 = QtWidgets.QWidget()
        self.w5.setStyleSheet("image: url(:/features/Features/5.png);")
        self.w5.setObjectName("w5")
        self.what_isnew.addWidget(self.w5)
        self.next_feature = QtWidgets.QPushButton(self.whatnews_frame)
        self.next_feature.setGeometry(QtCore.QRect(240, 220, 30, 30))
        self.next_feature.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    background-color:#0055FF;\n"
"    background-image: url(:/cils/cils/cil-chevron-circle-right-alt.png);\n"
"    background-position:center;\n"
"    background-repeat:no-repeat;\n"
"}")
        self.next_feature.setText("")
        self.next_feature.setObjectName("next_feature")
        self.prev_feature = QtWidgets.QPushButton(self.whatnews_frame)
        self.prev_feature.setGeometry(QtCore.QRect(6, 220, 30, 30))
        self.prev_feature.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    background-color:#0055FF;\n"
"    background-image: url(:/cils/cils/cil-chevron-circle-left-alt.png);\n"
"    background-position:center;\n"
"    background-repeat:no-repeat;\n"
"}")
        self.prev_feature.setText("")
        self.prev_feature.setObjectName("prev_feature")
        self.terminate = QtWidgets.QPushButton(self.whatnews_frame)
        self.terminate.setGeometry(QtCore.QRect(70, 506, 131, 41))
        self.terminate.setStyleSheet("QPushButton{\n"
"    border:none; \n"
"    border-radius:20px; \n"
"    font-size:18px; \n"
"    font-weight:bold;\n"
"    padding-left:15px;\n"
"    padding-right:15px; \n"
"    background-color:rgba(57, 146, 240, 180);\n"
"    color:#FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border:2px solid rgba(57, 146, 240, 250); \n"
"    font-weight:0;\n"
"    background-color:#FFFFFF;\n"
"    color:rgba(57, 146, 240, 250);\n"
"}")
        self.terminate.setObjectName("terminate")
        self.current_feature = QtWidgets.QFrame(self.whatnews_frame)
        self.current_feature.setGeometry(QtCore.QRect(65, 463, 141, 21))
        self.current_feature.setStyleSheet("background:none;\n"
"outline:none;")
        self.current_feature.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.current_feature.setFrameShadow(QtWidgets.QFrame.Raised)
        self.current_feature.setObjectName("current_feature")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.current_feature)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.feature_0 = QtWidgets.QPushButton(self.current_feature)
        self.feature_0.setMinimumSize(QtCore.QSize(15, 15))
        self.feature_0.setMaximumSize(QtCore.QSize(15, 15))
        self.feature_0.setStyleSheet("QPushButton{\n"
"    background-color:#EAEAEA;\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#3385CC;\n"
"}")
        self.feature_0.setText("")
        self.feature_0.setObjectName("feature_0")
        self.horizontalLayout.addWidget(self.feature_0)
        self.feature_1 = QtWidgets.QPushButton(self.current_feature)
        self.feature_1.setMinimumSize(QtCore.QSize(15, 15))
        self.feature_1.setMaximumSize(QtCore.QSize(15, 15))
        self.feature_1.setStyleSheet("QPushButton{\n"
"    background-color:#EAEAEA;\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#3385CC;\n"
"}")
        self.feature_1.setText("")
        self.feature_1.setObjectName("feature_1")
        self.horizontalLayout.addWidget(self.feature_1)
        self.feature_2 = QtWidgets.QPushButton(self.current_feature)
        self.feature_2.setMinimumSize(QtCore.QSize(15, 15))
        self.feature_2.setMaximumSize(QtCore.QSize(15, 15))
        self.feature_2.setStyleSheet("QPushButton{\n"
"    background-color:#EAEAEA;\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#3385CC;\n"
"}")
        self.feature_2.setText("")
        self.feature_2.setObjectName("feature_2")
        self.horizontalLayout.addWidget(self.feature_2)
        self.feature_3 = QtWidgets.QPushButton(self.current_feature)
        self.feature_3.setMinimumSize(QtCore.QSize(15, 15))
        self.feature_3.setMaximumSize(QtCore.QSize(15, 15))
        self.feature_3.setStyleSheet("QPushButton{\n"
"    background-color:#EAEAEA;\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#3385CC;\n"
"}")
        self.feature_3.setText("")
        self.feature_3.setObjectName("feature_3")
        self.horizontalLayout.addWidget(self.feature_3)
        self.feature_4 = QtWidgets.QPushButton(self.current_feature)
        self.feature_4.setMinimumSize(QtCore.QSize(15, 15))
        self.feature_4.setMaximumSize(QtCore.QSize(15, 15))
        self.feature_4.setStyleSheet("QPushButton{\n"
"    background-color:#EAEAEA;\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#3385CC;\n"
"}")
        self.feature_4.setText("")
        self.feature_4.setObjectName("feature_4")
        self.horizontalLayout.addWidget(self.feature_4)
        self.feature_5 = QtWidgets.QPushButton(self.current_feature)
        self.feature_5.setMinimumSize(QtCore.QSize(15, 15))
        self.feature_5.setMaximumSize(QtCore.QSize(15, 15))
        self.feature_5.setStyleSheet("QPushButton{\n"
"    background-color:#EAEAEA;\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#3385CC;\n"
"}")
        self.feature_5.setText("")
        self.feature_5.setObjectName("feature_5")
        self.horizontalLayout.addWidget(self.feature_5)
        self.stackedWidget.addWidget(self.page_3)
        self.main_title = QtWidgets.QLabel(SigninWindow)
        self.main_title.setGeometry(QtCore.QRect(0, 4, 275, 41))
        self.main_title.setStyleSheet("color: rgb(51, 153, 204);\n"
"background-color: rgb(255, 255, 255);\n"
"font-size:20px; \n"
"font-weight:bold; \n"
"font-family: Kirvy;\n"
"padding-right:10px;\n"
"border-top-left-radius:12px;\n"
"border-top-right-radius:12px;\n"
"")
        self.main_title.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.main_title.setObjectName("main_title")
        self.return_button = QtWidgets.QPushButton(SigninWindow)
        self.return_button.setGeometry(QtCore.QRect(2, 12, 26, 26))
        self.return_button.setStyleSheet("QPushButton{\n"
"    image: url(:/cils/cils/cil-arrow-circle-left.png);\n"
"    border-radius:13px;\n"
"    background:none;\n"
"    color:none;\n"
"    border:none;}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#3399CC;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:grey;\n"
"}")
        self.return_button.setText("")
        self.return_button.setObjectName("return_button")

        self.retranslateUi(SigninWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.code.setCurrentIndex(0)
        self.what_isnew.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SigninWindow)

    def retranslateUi(self, SigninWindow):
        _translate = QtCore.QCoreApplication.translate
        SigninWindow.setWindowTitle(_translate("SigninWindow", "Signin"))
        self.create_account.setText(_translate("SigninWindow", "Créez votre compte sans tarder."))
        self.user_name.setToolTip(_translate("SigninWindow", "Saisissez votre nom d\'utilisateur."))
        self.user_name.setPlaceholderText(_translate("SigninWindow", "Nom d\'utilisateur"))
        self.code.setToolTip(_translate("SigninWindow", "Choisissez votre nom de code.\n"
"Ce nom doit être unique pour chaque compte."))
        self.code.setCurrentText(_translate("SigninWindow", "Nom de code"))
        self.code.setItemText(1, _translate("SigninWindow", "Alpha"))
        self.code.setItemText(2, _translate("SigninWindow", "Bravo"))
        self.code.setItemText(3, _translate("SigninWindow", "Charlie"))
        self.code.setItemText(4, _translate("SigninWindow", "Delta"))
        self.code.setItemText(5, _translate("SigninWindow", "Echo"))
        self.code.setItemText(6, _translate("SigninWindow", "FoxTrot"))
        self.code.setItemText(7, _translate("SigninWindow", "Golf"))
        self.code.setItemText(8, _translate("SigninWindow", "Hotel"))
        self.code.setItemText(9, _translate("SigninWindow", "India"))
        self.code.setItemText(10, _translate("SigninWindow", "Juliet"))
        self.code.setItemText(11, _translate("SigninWindow", "Kilo"))
        self.code.setItemText(12, _translate("SigninWindow", "Lima"))
        self.code.setItemText(13, _translate("SigninWindow", "Mike"))
        self.code.setItemText(14, _translate("SigninWindow", "November"))
        self.code.setItemText(15, _translate("SigninWindow", "Oscar"))
        self.code.setItemText(16, _translate("SigninWindow", "Papa"))
        self.code.setItemText(17, _translate("SigninWindow", "Quebec"))
        self.code.setItemText(18, _translate("SigninWindow", "Romeo"))
        self.code.setItemText(19, _translate("SigninWindow", "Sierra"))
        self.code.setItemText(20, _translate("SigninWindow", "Tango"))
        self.code.setItemText(21, _translate("SigninWindow", "Uniform"))
        self.code.setItemText(22, _translate("SigninWindow", "Victor"))
        self.code.setItemText(23, _translate("SigninWindow", "Whisky"))
        self.code.setItemText(24, _translate("SigninWindow", "X-ray"))
        self.code.setItemText(25, _translate("SigninWindow", "Yankee"))
        self.code.setItemText(26, _translate("SigninWindow", "Zulu"))
        self.passcode.setToolTip(_translate("SigninWindow", "Saisissez votre mot de passe.\n"
"Utilisez un mot de passe facile à retenir."))
        self.passcode.setPlaceholderText(_translate("SigninWindow", "Mot de passe"))
        self.passcode2.setToolTip(_translate("SigninWindow", "Saisissez de nouveau votre mot de passe."))
        self.passcode2.setPlaceholderText(_translate("SigninWindow", "Confirmer mot de passe"))
        self.welcome.setText(_translate("SigninWindow", "Bienvenue dans la révolution !"))
        self.choose_profilepicture.setToolTip(_translate("SigninWindow", "<html><head/><body><p>Avatar (PRO)</p></body></html>"))
        self.next.setText(_translate("SigninWindow", "Suivant"))
        self.read_carefuly.setText(_translate("SigninWindow", "Lisez attentivement ces termes."))
        self.cgu.setText(_translate("SigninWindow", "Termes du contrat de licence."))
        self.validate.setText(_translate("SigninWindow", "Valider"))
        self.textBrowser.setHtml(_translate("SigninWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16px; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; font-weight:600;\">CONDITIONS GENERALES D\'UTILISATION  DU LOGICIEL &quot;AR Intercom&quot;</span><span style=\" font-size:12pt;\"> </span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; font-weight:600;\">=====================================</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\">Nom         : AR Intercom</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\">Version         : 2.0</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\">Nom de version    : Kivringo</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\">Mise à jour     : 24-10-2021</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\">Auteur        : Antares Mugisho</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\">E-mail auteur    : antaresmugisho@gmail.com</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\">Editeur        : Art Revolution Label</span><span style=\" font-size:12pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\">Site web        : </span><a href=\"http://www.arintercom.org\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; text-decoration: underline; color:#0000ff;\">www.artrevolution.one</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\">Licence         : Libre</span><span style=\" font-size:12pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; font-weight:600;\">=====================================</span><span style=\" font-size:12pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> </span><span style=\" font-size:12pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; font-weight:600; color:#333333;\">Article 1</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\"> : </span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; font-weight:600; color:#333333;\">Objet</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\">Les présentes CGU ou Conditions Générales d’Utilisation encadrent juridiquement l’utilisation des services du logiciel de messagerie intannée &quot;</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; font-weight:600; color:#333333;\">AR Intercom</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\">&quot; (ci-après dénommé « le logiciel »).</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\">Constituant le contrat entre la société Art Revolutin Label et le dernier Utilisateur, l’accès au logiciel doit être précédé de l’acceptation de ces CGU. L’accès à cette plateforme signifie l’acceptation des présentes CGU.</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; background-color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; font-weight:600; color:#333333;\">Article 2</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\"> : </span><a href=\"https://www.legalplace.fr/guides/mentions-legales/\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#c00000;\">Mentions légales</span></a><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; font-weight:600; color:#c00000;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\">L’édition du logiciel Art Revolutuion Intercom est assurée par la société Art Revolution Label inscrite au RCCM, dont le siège social est localisé à Goma, Quartier Katoyi, Av. Bakisi, N°55 dans la Province du Nord-Kivu, en République Démocraique du Congo.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333; background-color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; font-weight:600; color:#333333;\">Article 3</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\"> : Accès au logiciel</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\">Le logiciel AR Intercom est fait pour permettre à l’utilisateur de communiquer gratuitement avec un autre disposant du même logiciel. Les informations échangées peuvent être des textes écrits ou des fichiers multimédia entre autres les images, les médias audio, des médias visuels et autres types de donnée multimédia.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333; background-color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\">Les services du logiciel sont accessibles gratuitement par tout utilisateur disposant d\'abord d\'un compte AR intercom puis d’un accès au réseau local de l\'entreprise. Tous les frais éventuels nécessaires pour l’accès aux services (matériel informatique, connexion Internet…) sont à la charge de l’utilisateur.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333; background-color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\">L’accès aux services dédiés aux utilisateurs s’effectue à l’aide d’un identifiant (Nom d\'utilisateur) et d’un mot de passe préalablement définis par l’utilisateur lors de sa première utilisation du logiciel.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333; background-color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\">Pour des raisons de maintenance ou autres, l’accès au logiciel peut être interrompu ou suspendu par l’éditeur sans préavis ni justification.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333; background-color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; font-weight:600; color:#333333;\">Article 4</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\"> : Collecte des données</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\">Pour la création du compte de l’Utilisateur, la collecte des informations au moment de l’inscription sur le logiciel est nécessaire et obligatoire. Conformément à la loi n°78-17 du 6 janvier relative à l’informatique, aux fichiers et aux libertés, la collecte et le traitement d’informations personnelles s’effectuent dans le respect de la vie privée.</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; background-color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\">Suivant la loi Informatique et Libertés en date du 6 janvier 1978, articles 39 et 40, l’Utilisateur dispose du droit d’accéder, de rectifier, de supprimer et d’opposer ses données personnelles. L’exercice de ce droit s’effectue par le menu &quot;Mon Compte&quot; disponible dans les menus du logiciel.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-size:12pt; background-color:#ffffff;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; font-weight:600; color:#333333;\">Article 5</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\"> : Propriété intellectuelle</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\">Les marques, logos ainsi que les contenus du logiciel AR Intercom (illustrations graphiques, textes…) sont protégés par le Code de la propriété intellectuelle et par le droit d’auteur.</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\">La reproduction ou la copie des contenus par l’Utilisateur requièrent une autorisation préalable de l\'éditeur. Dans ce cas, toute utilisation à des usages commerciaux ou à des fins publicitaires est proscrite.</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; background-color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; font-weight:600; color:#333333;\">Article 6</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\"> : Responsabilité</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\">Bien que les informations échangées entre utilisateurs soient réputées fiables, le logiciel se réserve la faculté d’une non-garantie de la fiabilité des sources.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\">En dépit des mises à jour régulières, la responsabilité du logiciel ne peut être engagée en cas de modification des dispositions administratives et juridiques apparaissant après la publication. Il en est de même pour l’utilisation et l’interprétation des informations communiquées sur la plateforme.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\">Le logiciel décline toute responsabilité concernant les éventuels virus pouvant infecter le matériel informatique de l’Utilisateur après l’utilisation ou l’accès à ce logiciel.</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\">Le logiciel ne peut être tenu pour responsable en cas de force majeure ou du fait imprévisible et insurmontable d’un tiers.</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; background-color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\">La garantie totale de la sécurité et la confidentialité des données n’est pas assurée par le logiciel. Cependant, le logiciel s’engage à mettre en œuvre toutes les méthodes requises pour le faire au mieux.</span><span style=\" font-size:12pt;\"> </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; background-color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; font-weight:600; color:#333333;\">Article 7</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\"> : Liens hypertextes</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\">Le logiciel peut être constitué de liens hypertextes. En cliquant sur ces derniers, l’Utilisateur sortira de la plateforme. Cette dernière n’a pas de contrôle et ne peut pas être tenue responsable du contenu des pages web relatives à ces liens.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; font-weight:600; color:#333333;\">Article 08</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\"> : Durée du contrat</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\">Le présent contrat est valable pour une durée indéterminée. L\'acceptation de ces termes par l\'Utilisateur marque l’application du contrat à son égard.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; font-weight:600; color:#333333;\">Article 09</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\"> : Droit applicable et juridiction compétente</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\">Le présent contrat est soumis à la législation congolaise. L’absence de résolution à l’amiable des cas de litige entre les parties implique le recours aux tribunaux congolais compétents pour régler le contentieux.</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> </span><span style=\" font-size:12pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; background-color:#ffffff;\">L\'éditeur</span><span style=\" font-size:12pt;\"> </span></p>\n"
"<p align=\"right\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt; color:#333333;\">©</span><span style=\" font-family:\'Arial Narrow\',\'sans-serif\'; font-size:12pt;\"> 2021, AR Intercom</span><span style=\" font-size:12pt;\"> </span></p></body></html>"))
        self.iaggree.setText(_translate("SigninWindow", "J\'accepte les termes de ce contrat."))
        self.cgu_2.setText(_translate("SigninWindow", "Change log"))
        self.read_carefuly_2.setText(_translate("SigninWindow", "Quoi de neuf ?"))
        self.terminate.setText(_translate("SigninWindow", "Terminer"))
        self.main_title.setText(_translate("SigninWindow", "Art Revolution Intercom"))
from resources import img_rc
